language: node_js
node_js:
- lts/*
script:
- npm run cover
- npm run coveralls
deploy:
  skip_cleanup: true
  provider: npm
  email: julien.blin@gmail.com
  api_key:
    secure: c3x6onbZEB31jp9utvxJMMM3v3FtkxHXr4BZ6v3sPI/rvEsnY/rsUQHzOUkV3rUIRW+5h7PV1hWPTx4Ztxp4KaRHSfB1DR1lZIKauyIsxFeBu0YNqnXpAD9Z1oW/04WTeEJzG/TznmalUDD07tBWqG7+ORBulZs0f1qhQw4oV8iFRi0L3RrBBiQ5XU/3mtc44vtb518to2K3WFgbrB3CrkjVymq9cLL1xzm9nWtqlhCMPUt/booSSd3r8MMrMAhupCMSsAGDAalH6ZWrEGBgOEQZ5cRgONBcMBbjmughJMB4HlidPq5zrZCYq1rY1YLIKISpH2udrXw27dy+oxDWY9LMagPjYn8rkFMPs1j4SZo22Fs8fY4dpb67CdPP16cHgBUUzYXhU656GD66z83/fR8388xEb/n8055lAfg56N6Pc2DYBrxs3J9XAYBWs2QOkcyuz7zu/+zdX1LjLc91RiRlXR+9o1iWwaidf0BNOdrtL+Ndy71vu+gvMa177J/5CbL/ivApJ5wmz2X2h2p3ASFHnnSzGj4+KgeANfOl3+OhJWziLyd6eW2GN4U9KRUyX5SSDIRnrUXLQLD7huPpqaSPsY6ODDNni6+X9iCy/TGL7kCR2n3aaK87RGLyirYOZUhG8sy39sr7tYmAa3j6qrhUWxMZJWrDfeVp23o7UN0=
  on:
    tags: true
    repo: julienblin/opiniated-lambda
